# Generated by Django 2.2.1 on 2019-08-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190731_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='First Name', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='Last Name', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_intro',
            field=models.TextField(default='Default intro. Change this to tell other users a little more about yourself'),
        ),
    ]
