# Generated by Django 2.2.1 on 2019-08-08 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190806_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
