# Generated by Django 2.2.1 on 2019-08-08 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_address_line_one', models.CharField(max_length=50)),
                ('job_address_town', models.CharField(max_length=30)),
                ('job_address_county', models.CharField(max_length=25)),
                ('job_address_postcode', models.CharField(max_length=10)),
                ('job_image', models.ImageField(default='job-default.jpg', upload_to='job_images')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
