# Generated by Django 2.2.1 on 2019-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfileupload',
            name='file_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
        ),
        migrations.DeleteModel(
            name='JobBid',
        ),
    ]
