# Generated by Django 2.2.1 on 2019-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_overview',
            field=models.CharField(default='Default Project Overview', max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='Default Project Name', max_length=100),
        ),
    ]
