# Generated by Django 2.2.1 on 2019-08-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190808_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_address_county',
            new_name='job_location_county',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_address_town',
            new_name='job_location_town',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_address_line_one',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_address_postcode',
        ),
    ]
