# Generated by Django 2.2.1 on 2019-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='jobcomment',
            options={'ordering': ['-comment_date']},
        ),
    ]
