# Generated by Django 2.2.1 on 2019-08-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobbid',
            name='job_name',
        ),
    ]
