# Generated by Django 2.2.1 on 2019-09-02 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190829_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfileupload',
            name='author',
            field=models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobfileupload',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='jobs.Job'),
        ),
    ]
