# Generated by Django 2.2.1 on 2019-08-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobbid_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_image',
            new_name='image',
        ),
    ]
