# Generated by Django 2.2.1 on 2019-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog_default.jpg', upload_to='blog_images'),
        ),
    ]
