# Generated by Django 2.2.1 on 2019-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-comment_date']},
        ),
    ]
