# Generated by Django 2.2.1 on 2019-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.ImageField(default='blog-default.jpg', upload_to='blog_images'),
        ),
    ]
