# Generated by Django 2.2.1 on 2019-08-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default='Default intro input for blog posts', max_length=250),
        ),
    ]
