# Generated by Django 2.2.1 on 2019-08-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190805_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_image',
            new_name='image',
        ),
    ]
